#!/bin/bash

if ["${BUILD_FOLDER}" == ""]; then
    BUILD_FOLDER=".buildroot/build_rpi"
fi

if ["${DEFCONFIG}" == ""]; then
    DEFCONFIG="raspberrypi_defconfig"
fi

echo "BUILD_FOLDER = ${BUILD_FOLDER}"
echo "DEFCONFIG = ${DEFCONFIG}"

mkdir -p /home/${BUILD_FOLDER}
cd /home/${BUILD_FOLDER}

make O=$(pwd) -C /buildroot ${DEFCONFIG}
make
